# --- Параметры Модели ---
model_weight: "yolo11n.pt"  # С каких весов начинаем (можно yolo8n.pt)

# --- Основные параметры обучения ---
data: "dataset.yaml"        # Путь к файлу с путями к картинкам
epochs: 200                 # Максимум эпох
patience: 60                # Остановка, если нет улучшений 20 эпох
batch: 16                  # Размер батча
imgsz: 640                  # Размер картинки
device: "cpu"                   # 0 для GPU, 'cpu' для процессора

# --- Настройки оптимизатора ---
optimizer: "AdamW"          # Лучше работает на малых данных
lr0: 0.001                  # Стандартный learning rate
dropout: 0.1                # Добавим немного "забывания", чтобы бороться с переобучением (важно для 80 фото!)

# --- Логирование и Сохранение ---
project: "my_project"       # Папка проекта
name: "yolo11n_custom"      # Имя папки с результатами
exist_ok: True              # Перезаписывать, если папка уже есть

# --- Тонкая настройка (для маленьких датасетов) ---
freeze: 10                  # Заморозить 10 слоев (Backbone). Поставьте 0, чтобы выключить.
seed: 42                    # Фиксируем случайность для воспроизводимости

# --- Augmentation ---

# 1. ОТРАЖЕНИЯ (Зеркала) — ВЫКЛЮЧИТЬ СТРОГО
fliplr: 0.0       # Нельзя, иначе E превратится в Ǝ
flipud: 0.0       # Нельзя, иначе N превратится в перевернутую N

# 2. ПОВОРОТЫ — ВКЛЮЧИТЬ
degrees: 180.0    # Можно крутить компас хоть вверх ногами (+/- 180 градусов).
# Это ОЧЕНЬ поможет увеличить ваш маленький датасет.

# 3. МАСШТАБ И СМЕЩЕНИЕ
scale: 0.5        # Компас может быть близко к камере или далеко. (важно!)
translate: 0.1    # Немного двигать влево-вправо.

# 4. ЦВЕТ И СВЕТ (Важно для реальных фото)
hsv_h: 0.015      # Чуть менять оттенок
hsv_s: 0.7        # Менять насыщенность (тусклый свет / яркий свет)
hsv_v: 0.4        # Менять яркость (тень / солнце)

# 5. СЛОЖНЫЕ ТЕХНИКИ
mosaic: 1.0       # Оставляем. Склеивает 4 фото в 1.
perspective: 0.0005 # ОЧЕНЬ ПОЛЕЗНО ДЛЯ КОМПАСА!
# Это имитирует взгляд на компас не строго сверху, а под углом (сбоку).
# Значение маленькое (0.0005 - 0.001), иначе исказит слишком сильно.